/**
 * Compiles the stylesheet (Tailwind) and the JavaScript icon set. This is a DEVELOPER step only: the compiled output
 * (public_html/assets/css/app.css, public_html/assets/js/icons.js) is committed, so the hosted site needs no build at all.
 *
 *   node migration-tools/build-css.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";

const from = new URL("./tailwind.css", import.meta.url).pathname;
const css = readFileSync(from, "utf8");
const out = await postcss([tailwind({ optimize: { minify: true } })]).process(css, { from, to: "public_html/assets/css/app.css" });
writeFileSync("public_html/assets/css/app.css", out.css);
console.log(`app.css  ${(out.css.length / 1024).toFixed(1)} KB`);

// the same icon set the PHP views use, for icons created by the browser-side code
const icons = JSON.parse(readFileSync("public_html/app/data/icons.json", "utf8"));
writeFileSync("public_html/assets/js/icons.js", "/* generated by migration-tools/build-css.mjs — do not edit */\nwindow.FE_ICONS=" + JSON.stringify(icons) + ";\n");
console.log(`icons.js ${Object.keys(icons).length} icons`);
