/** Bootstrap content: real, honest, editable defaults. No metrics, no fake clients, no invented prices. */

export interface ServiceSeed {
  slug: string;
  title: string;
  icon: string;
  shortDescription: string;
  description: string;
  useCase: string;
  turnaround: string;
  deliverables: string[];
  whoFor: string[];
  included: string[];
  exampleDeliverables: string[];
  platforms: string[];
  editingStyle: string;
  addOns: string[];
  workflow: string[];
  faqCategory: string;
  onboardingCategories: string[];
  featured?: boolean;
}

const WORKFLOW = ["Send your footage and brief through your portal", "We confirm scope and timeline in a fixed-price quote", "Your editor delivers a first draft for timestamped review", "Request revisions directly on the timeline", "Approve the final version and download all files"];

export const SERVICES: ServiceSeed[] = [
  {
    slug: "short-form-video-editing",
    title: "Short-Form Editing",
    icon: "smartphone",
    shortDescription: "Scroll-stopping vertical edits for Reels, Shorts and TikTok — built around a strong hook and clean captions.",
    description: "Short-form lives or dies in the first two seconds. We cut for retention: tight pacing, hook-first structure, on-brand captions, sound design and motion that support the message instead of distracting from it. Send us long recordings or raw clips and we return batches that are ready to post.",
    useCase: "Creators, coaches and brands publishing several vertical videos each week.",
    turnaround: "48–72 hours per batch",
    deliverables: ["9:16 vertical exports", "Animated captions", "Sound design & music", "Hook optimisation", "CTA animation"],
    whoFor: ["Creators repurposing long videos into clips", "Coaches and consultants building authority", "Brands running organic short-form", "Agencies that need a reliable vertical-video partner"],
    included: ["9:16 export (plus 1:1 / 4:5 on request)", "Captions in your brand style", "Motion graphics & callouts", "Sound design and licensed music", "B-roll and transitions", "Colour correction", "Hook optimisation", "CTA animation", "Two included revision rounds"],
    exampleDeliverables: ["10 Reels cut from one interview", "Weekly Shorts batch from your podcast", "Product teaser series", "Client testimonial snippets"],
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts", "LinkedIn clips", "Vertical ads"],
    editingStyle: "Fast, punchy and readable on mute. We match your voice: from clean and minimal to high-energy with kinetic type.",
    addOns: ["Thumbnail / cover frames", "Extra formats (1:1, 4:5)", "Rush delivery", "Posting schedule & captions copy"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["SHORT_FORM", "CREATOR"],
    featured: true,
  },
  {
    slug: "youtube-video-editing",
    title: "Long-Form YouTube",
    icon: "play",
    shortDescription: "Retention-focused editing for YouTube: pacing, story structure, b-roll, sound and thumbnails-ready exports.",
    description: "We edit YouTube videos to hold attention from cold open to final CTA: tightening dead air, adding pattern interrupts, layering b-roll, graphics and sound design, and keeping the story clear. Your channel style stays consistent across every upload.",
    useCase: "Channels publishing weekly or bi-weekly long-form videos.",
    turnaround: "3–5 business days",
    deliverables: ["Master 16:9 edit up to 4K", "Chapters & timestamps", "Captions / SRT file", "Optional thumbnail", "Optional Shorts cutdowns"],
    whoFor: ["Educators and explainers", "Commentary and documentary channels", "Business and finance creators", "Personal brands growing on YouTube"],
    included: ["Story and pacing pass", "B-roll, stock and screen-recording integration", "Motion graphics & lower thirds", "Sound design, music and mix", "Colour correction", "Captions (SRT)", "Two included revision rounds"],
    exampleDeliverables: ["12-minute explainer", "Weekly commentary episode", "Course lesson series", "Documentary-style story"],
    platforms: ["YouTube"],
    editingStyle: "Story-first. We plan hooks, open loops and chapters so viewers stay to the end.",
    addOns: ["Thumbnail design", "Shorts cutdowns", "Title & description drafting", "Channel style guide"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["CREATOR", "YOUTUBE"],
    featured: true,
  },
  {
    slug: "podcast-editing",
    title: "Podcast Editing",
    icon: "mic",
    shortDescription: "Full-episode video and audio edits, multicam switching, cleanup, and social clips from every recording.",
    description: "We turn raw recordings into polished episodes: multicam switching, noise and level cleanup, filler-word trimming, intros and outros, plus vertical clips for social. One recording becomes a full episode, a YouTube cut and a week of clips.",
    useCase: "Video and audio podcasts that want a consistent release cadence.",
    turnaround: "3–4 business days per episode",
    deliverables: ["Full episode (video + audio)", "YouTube version", "Social clips", "Audio cleanup", "Captions"],
    whoFor: ["Interview and co-hosted shows", "Branded company podcasts", "Podcasters moving to video"],
    included: ["Multicam switching & sync", "Audio cleanup & levelling", "Intro / outro placement", "Chapters and show-note timestamps", "Captions", "Highlight clips", "Two included revision rounds"],
    exampleDeliverables: ["Full episode + 3 clips", "Audio-only feed", "YouTube cut with chapters"],
    platforms: ["YouTube", "Spotify", "Apple Podcasts", "Instagram", "TikTok", "LinkedIn"],
    editingStyle: "Clean, natural and conversation-first — the edit should disappear.",
    addOns: ["Show notes & titles", "Thumbnail design", "Audiograms", "Extra clips"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["PODCAST"],
    featured: true,
  },
  {
    slug: "real-estate-video-editing",
    title: "Real Estate Video",
    icon: "home",
    shortDescription: "Cinematic listing tours, agent intros and social reels — branded, fast and MLS-friendly.",
    description: "Properties sell faster when the video feels premium. We edit walkthroughs, cinematic tours, drone sequences and agent-branded reels with clean colour, smooth transitions and on-screen details that matter to buyers.",
    useCase: "Agents, brokerages and photographers delivering listing videos at pace.",
    turnaround: "24–72 hours per listing",
    deliverables: ["Horizontal tour", "Vertical social reel", "MLS-compliant version", "Agent branding", "Music-licensed exports"],
    whoFor: ["Real-estate agents and teams", "Property photographers and videographers", "Luxury developers and short-let hosts"],
    included: ["Colour correction & sky/exposure fixes", "Agent branding and lower thirds", "Drone and interior sequencing", "Licensed music", "Horizontal and vertical exports", "Two included revision rounds"],
    exampleDeliverables: ["90-second listing tour", "30-second Instagram reel", "Agent introduction + featured listing"],
    platforms: ["MLS", "YouTube", "Instagram", "Facebook", "TikTok"],
    editingStyle: "Bright, clean and cinematic — smooth movement, honest colour, no gimmicks.",
    addOns: ["Twilight sky replacement", "Neighbourhood highlight", "Floor-plan animation", "Rush delivery"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["REAL_ESTATE"],
    featured: true,
  },
  {
    slug: "corporate-video-editing",
    title: "Corporate Video",
    icon: "building",
    shortDescription: "Brand films, internal comms, training and executive messages — polished and on-brand.",
    description: "We edit corporate content with an eye for clarity and brand consistency: interviews, explainers, training modules, recruitment and event recaps, all aligned to your guidelines and review process.",
    useCase: "Marketing and comms teams that need reliable, brand-safe video.",
    turnaround: "5–7 business days",
    deliverables: ["Master edit", "Brand-compliant graphics", "Captions", "Alt cutdowns", "Source files (if agreed)"],
    whoFor: ["Marketing and communications teams", "HR & L&D departments", "Agencies serving corporate clients"],
    included: ["Interview editing", "Brand graphics & lower thirds", "Captions & accessibility", "Stakeholder review workflow", "Two included revision rounds"],
    exampleDeliverables: ["Brand film", "Training module series", "Executive update", "Event recap"],
    platforms: ["Website", "LinkedIn", "Intranet", "YouTube"],
    editingStyle: "Polished, calm and credible.",
    addOns: ["Multiple language captions", "Cutdowns for social", "Legal/brand review rounds"],
    workflow: WORKFLOW,
    faqCategory: "Contracts",
    onboardingCategories: ["CORPORATE"],
  },
  {
    slug: "saas-video-editing",
    title: "SaaS / Product Video",
    icon: "monitor",
    shortDescription: "Product demos, explainers and launch videos with clean UI animation and clear storytelling.",
    description: "We turn screen recordings and product footage into clear, compelling stories: focused zooms and callouts, UI animations, voiceover sync and motion graphics that explain what your product does in seconds.",
    useCase: "Startups and SaaS teams launching features, demos and onboarding videos.",
    turnaround: "4–6 business days",
    deliverables: ["Product demo", "Explainer", "Feature announcement", "Onboarding tutorial", "Social cutdowns"],
    whoFor: ["Product-led SaaS companies", "Early-stage founders", "Customer-success and onboarding teams"],
    included: ["Screen-recording polish", "UI animation & callouts", "Voiceover sync", "Captions", "Brand-consistent motion graphics", "Two included revision rounds"],
    exampleDeliverables: ["60-second product demo", "Feature launch video", "Onboarding walkthrough"],
    platforms: ["Website", "Product Hunt", "YouTube", "LinkedIn", "In-app"],
    editingStyle: "Crisp, modern and focused on outcomes, not features.",
    addOns: ["AI or human voiceover", "Product mockup animation", "Localised versions"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["SAAS"],
  },
  {
    slug: "vsl-editing",
    title: "VSL Editing",
    icon: "megaphone",
    shortDescription: "Direct-response video sales letters with persuasive pacing, proof and clear calls to action.",
    description: "A great VSL keeps attention and moves viewers toward one action. We structure pacing, on-screen text, proof elements and pattern interrupts around your script so the message lands and the offer is clear.",
    useCase: "Coaches, info-product owners and DTC brands running direct-response funnels.",
    turnaround: "5–8 business days",
    deliverables: ["VSL master", "Text-on-screen version", "Alternate hooks", "Captions"],
    whoFor: ["Info-product and course creators", "Coaches & consultants", "Direct-response marketers"],
    included: ["Script-based structure", "On-screen text & emphasis", "Proof and testimonial integration", "Sound design & music", "Two included revision rounds"],
    exampleDeliverables: ["12-minute VSL", "Hook A/B variants", "Mobile-first cut"],
    platforms: ["Landing pages", "Funnels", "Paid social"],
    editingStyle: "Clear, persuasive and paced for attention.",
    addOns: ["Extra hook variants", "Voiceover", "Stock & b-roll sourcing"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["VSL"],
  },
  {
    slug: "ugc-editing",
    title: "UGC Editing",
    icon: "users",
    shortDescription: "Authentic, high-converting UGC-style edits for paid social and organic.",
    description: "We polish creator-shot footage into native-feeling ads and posts: tight hooks, captions, b-roll, product overlays and multiple hook variations for testing.",
    useCase: "E-commerce and DTC brands testing creative at volume.",
    turnaround: "48–72 hours",
    deliverables: ["Vertical UGC edits", "Hook variations", "Captions", "Product overlays"],
    whoFor: ["DTC and e-commerce brands", "Performance marketing teams", "UGC creators"],
    included: ["Hook variations", "Native-style captions", "B-roll & product inserts", "Audio cleanup", "Two included revision rounds"],
    exampleDeliverables: ["5 UGC ad variations", "Unboxing edit", "Testimonial ad"],
    platforms: ["TikTok", "Instagram", "Meta Ads", "YouTube Shorts"],
    editingStyle: "Native, raw and trustworthy — never over-produced.",
    addOns: ["Extra hooks", "Static thumbnails", "Rush delivery"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["ECOMMERCE", "ADS", "SHORT_FORM"],
  },
  {
    slug: "social-media-clips",
    title: "Social Media Clips",
    icon: "share",
    shortDescription: "Turn webinars, streams and long videos into a steady stream of on-brand clips.",
    description: "We find the moments worth sharing and format them for every platform, with captions, branding and titles — so one recording feeds your whole content calendar.",
    useCase: "Teams repurposing webinars, interviews and events.",
    turnaround: "2–4 business days",
    deliverables: ["Clip packs", "Captions", "Multi-format exports", "Titles"],
    whoFor: ["Marketing teams", "Coaches with recorded calls", "Event organisers"],
    included: ["Moment selection", "Captions & branding", "Multi-format exports", "Two included revision rounds"],
    exampleDeliverables: ["10 clips from a webinar", "Event highlights"],
    platforms: ["LinkedIn", "Instagram", "TikTok", "YouTube Shorts", "X"],
    editingStyle: "Clean and consistent with your brand.",
    addOns: ["Posting copy", "Extra formats"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["SOCIAL", "SHORT_FORM"],
  },
  {
    slug: "motion-graphics",
    title: "Motion Graphics",
    icon: "sparkles",
    shortDescription: "Logo animations, lower thirds, kinetic type and explainers that lift any video.",
    description: "Custom motion design that matches your identity: animated logos, title systems, lower thirds, data visuals and short explainers — delivered as finished video and, where agreed, editable project files.",
    useCase: "Brands and creators who want a distinct, consistent motion language.",
    turnaround: "4–7 business days",
    deliverables: ["Logo animation", "Title packages", "Lower thirds", "Explainer animation", "Project files (if agreed)"],
    whoFor: ["Brands building a motion identity", "Creators wanting reusable graphics", "Agencies"],
    included: ["Storyboard / style frames", "Animation", "Sound design", "Export in requested formats", "Two included revision rounds"],
    exampleDeliverables: ["5-second logo sting", "Animated lower-third pack", "45-second explainer"],
    platforms: ["All platforms"],
    editingStyle: "Smooth, precise and brand-true.",
    addOns: ["Editable templates", "Alpha-channel exports"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["MOTION"],
  },
  {
    slug: "talking-head-editing",
    title: "Talking Head Editing",
    icon: "video",
    shortDescription: "Crisp jump-cuts, captions and light graphics for founder, coach and expert-led videos.",
    description: "Great talking-head videos feel effortless. We tighten delivery, remove filler, add light motion and captions, and keep your personality intact.",
    useCase: "Founders, coaches and experts publishing regularly to camera.",
    turnaround: "2–3 business days",
    deliverables: ["Edited video", "Captions", "Light graphics", "Audio cleanup"],
    whoFor: ["Founders & executives", "Coaches & consultants", "Educators"],
    included: ["Filler and silence removal", "Captions", "Audio cleanup", "Light motion & zooms", "Two included revision rounds"],
    exampleDeliverables: ["Weekly talking-head episode", "Founder update", "Course lesson"],
    platforms: ["YouTube", "LinkedIn", "Instagram", "Website"],
    editingStyle: "Natural and tight, with purposeful emphasis.",
    addOns: ["Thumbnails", "Clip cutdowns"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["CREATOR", "COACHING"],
  },
  {
    slug: "gaming-content-editing",
    title: "Gaming Content",
    icon: "gamepad",
    shortDescription: "High-energy gameplay edits: highlights, memes, sound effects and vertical clips.",
    description: "We turn hours of gameplay and stream footage into entertaining videos: highlight reels, comedic edits, montage sequences and vertical clips, with sound design that hits.",
    useCase: "Streamers and gaming channels growing on YouTube and Shorts.",
    turnaround: "3–5 business days",
    deliverables: ["Highlight videos", "Vertical clips", "Facecam layouts", "Thumbnails (optional)"],
    whoFor: ["Streamers", "Gaming channels", "Esports teams"],
    included: ["Moment selection", "Sound effects & music", "Facecam integration", "Captions & memes", "Two included revision rounds"],
    exampleDeliverables: ["Weekly highlight video", "Clip batch from a stream"],
    platforms: ["YouTube", "Twitch", "TikTok", "Shorts"],
    editingStyle: "Fast, funny and loud.",
    addOns: ["Thumbnail design", "Stream-to-shorts pipeline"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["GAMING", "CREATOR"],
  },
  {
    slug: "event-video-editing",
    title: "Event Editing",
    icon: "calendar",
    shortDescription: "Weddings, conferences and launches turned into highlight films and social teasers.",
    description: "We edit event footage into emotional, well-paced films: highlight reels, full ceremonies, speeches and quick social teasers — with careful audio and colour.",
    useCase: "Videographers and organisers who need dependable post-production.",
    turnaround: "5–10 business days",
    deliverables: ["Highlight film", "Full-length edit", "Teasers", "Speech edits"],
    whoFor: ["Wedding & event videographers", "Conference organisers", "Brands hosting launches"],
    included: ["Multicam sync", "Audio cleanup", "Colour grading", "Music licensing", "Two included revision rounds"],
    exampleDeliverables: ["4-minute wedding highlight", "Conference recap", "Social teaser"],
    platforms: ["YouTube", "Vimeo", "Instagram", "Website"],
    editingStyle: "Cinematic, warm and story-led.",
    addOns: ["Same-day teaser", "Extra formats"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["WEDDING"],
  },
  {
    slug: "ad-creative-editing",
    title: "Ad Creative Editing",
    icon: "target",
    shortDescription: "Performance-focused ad edits with fast iteration on hooks, formats and calls to action.",
    description: "We produce ad creative built to be tested: multiple hooks, formats and lengths, with clear offers, captions and CTAs — organised so your media buyer can launch quickly.",
    useCase: "Performance teams that need volume and speed in creative testing.",
    turnaround: "2–4 business days",
    deliverables: ["Ad variations", "Multiple aspect ratios", "Captions", "Hook tests"],
    whoFor: ["Performance marketers", "E-commerce brands", "Agencies"],
    included: ["Hook variations", "Multi-format exports", "Captions & overlays", "Brand safety checks", "Two included revision rounds"],
    exampleDeliverables: ["6 hook variants of one concept", "Retargeting cutdowns"],
    platforms: ["Meta", "TikTok", "YouTube", "Google"],
    editingStyle: "Direct, clear and built for testing.",
    addOns: ["Static cutdowns", "Rush delivery"],
    workflow: WORKFLOW,
    faqCategory: "Editing",
    onboardingCategories: ["ADS", "ECOMMERCE"],
  },
];

// ───────────────────────────── FAQs ─────────────────────────────

export const FAQS: { category: string; question: string; answer: string; serviceSlugs?: string[] }[] = [
  { category: "Pricing", question: "How is pricing calculated?", answer: "Every project gets a fixed-scope quote based on what you need: number and length of videos, complexity, deliverables and turnaround. You can also choose per-video or per-short pricing, or a monthly retainer for ongoing work. You'll see the full itemised price before anything starts." },
  { category: "Pricing", question: "Do you offer monthly plans?", answer: "Yes. Retainers include a set number of videos or shorts each month with a predictable price, priority scheduling and usage tracking in your portal. Ask about a retainer when you start a project or book a call." },
  { category: "Pricing", question: "Is there a deposit?", answer: "Projects are usually started with a deposit (shown in your quote) and the balance is invoiced when you approve the final version. Your quote states the exact split." },
  { category: "Turnaround", question: "How long does editing take?", answer: "Turnaround depends on the service and length — it's shown on each service page and confirmed in your quote. The clock starts when your project brief is complete and all required files are uploaded. Rush delivery may be available for an additional fee." },
  { category: "Turnaround", question: "What happens if I'm late sending files or feedback?", answer: "The timeline moves with you. We'll always show the expected draft date in your project and remind you if we're waiting on something." },
  { category: "Revisions", question: "How many revisions are included?", answer: "Your quote and contract state the included revision rounds — our standard is two. A round is one consolidated set of notes on a draft. You leave timestamped comments on the video and send them as a single revision request." },
  { category: "Revisions", question: "What if I want changes after approving?", answer: "Approval confirms the version meets the agreed requirements. After that, further changes are treated as a new request or a change order, which we'll quote separately." },
  { category: "Revisions", question: "What counts as a scope change?", answer: "Changing the agreed deliverables, adding new footage or formats, or altering the direction after production started is a scope change. Submit a change request in your project and we'll classify it as included, out of scope, or quote the extra cost." },
  { category: "Files", question: "How do I send my footage?", answer: "Upload directly from your project's Files tab — drag and drop with a progress bar, into folders like Raw Footage, Audio, Brand Assets and Music. Large files are sent straight to secure cloud storage." },
  { category: "Files", question: "What files should I send?", answer: "Raw footage or recordings, clean audio if recorded separately, your logo (PNG/SVG), brand colours and fonts, scripts or talking points, reference videos, and any music you want used. Your project setup form tells you exactly what's needed for your type of video." },
  { category: "Files", question: "Is my footage private?", answer: "Yes. Files are stored in access-controlled cloud storage and served through short-lived signed links. Only you, your team members and the studio staff assigned to your project can access them." },
  { category: "Files", question: "How long do you keep my files?", answer: "We keep your project files so repeat projects are fast. You can ask us to delete any project's files at any time." },
  { category: "Payments", question: "How does payment work?", answer: "After you accept a quote and sign the agreement, you'll receive an invoice in your portal. Payment activates your project. Any remaining balance is invoiced when you approve the final version." },
  { category: "Payments", question: "Which currencies and payment methods do you support?", answer: "Quotes and invoices can be issued in multiple currencies. Available payment methods depend on the studio's payment provider and are shown at checkout." },
  { category: "Editing", question: "Can you match my existing style?", answer: "Yes. Save your brand kit — logos, colours, fonts and music preferences — and share reference videos. We keep your style consistent across projects." },
  { category: "Editing", question: "Who edits my videos?", answer: "A named editor is assigned to your project and you can message them (or the project manager) right inside the project. Repeat clients keep the same editor where possible." },
  { category: "Editing", question: "Do you provide the project files?", answer: "Final videos, captions and requested formats are always delivered. Editable source files can be included if agreed in your quote." },
  { category: "Retainers", question: "How do retainer allowances work?", answer: "Your retainer includes a set number of videos, shorts or hours each month. Your dashboard shows what you've used, what's left, upcoming projects and your renewal date." },
  { category: "Retainers", question: "Can I pause or cancel a retainer?", answer: "Yes — retainers can be paused or cancelled according to your agreement. Contact us or message your project manager." },
  { category: "Contracts", question: "Do I need to sign a contract?", answer: "Yes. Each project has a short agreement covering scope, deliverables, turnaround, payment terms, revision limits, usage rights, confidentiality and cancellation. You can read, download and e-sign it from your portal." },
  { category: "Contracts", question: "Who owns the final videos?", answer: "You do. On full payment you receive a licence to use the final deliverables for your business purposes, as described in your agreement." },
  { category: "Editing", question: "Can you edit podcasts with multiple cameras?", answer: "Yes — we sync and switch multicam footage, clean the audio and produce the full episode, a YouTube version and social clips.", serviceSlugs: ["podcast-editing"] },
  { category: "Editing", question: "What formats do you deliver short-form in?", answer: "9:16 vertical by default, plus 1:1 and 4:5 on request, with captions burned in or delivered as a caption file.", serviceSlugs: ["short-form-video-editing", "ugc-editing", "social-media-clips"] },
  { category: "Editing", question: "Can you make MLS-compliant listing videos?", answer: "Yes. Tell us your MLS requirements and we'll deliver an unbranded, compliant version alongside your branded social edits.", serviceSlugs: ["real-estate-video-editing"] },
];

export const KB_ARTICLES: { slug: string; title: string; category: string; content: string }[] = [
  { slug: "how-do-i-upload-footage", title: "How do I upload footage?", category: "Files", content: "Open your project and choose the **Files** tab. Drag files into the upload area (or click to browse). Pick the right folder — Raw Footage, Audio, Brand Assets and so on — and watch the progress bar. Large files upload directly to secure storage, so you can close other tabs and keep working.\n\nWhen everything is up, click **I've uploaded everything** so your editor knows to start." },
  { slug: "how-many-revisions-are-included", title: "How many revisions are included?", category: "Revisions", content: "The number of included revision rounds is stated in your quote, contract and project header (our standard is two). A *round* is one consolidated set of notes on a draft.\n\nLeave timestamped comments while you watch, then press **Request revision** to send them all as one round." },
  { slug: "how-long-does-editing-take", title: "How long does editing take?", category: "Turnaround", content: "Your project header shows the expected draft date. Turnaround starts once your project brief is complete and your files are uploaded. If anything is missing, you'll see an **Action required** card on your dashboard." },
  { slug: "what-happens-after-approval", title: "What happens after I approve?", category: "Delivery", content: "Approving locks that version as final. If there is a remaining balance we'll invoice it, and once payment conditions are met your final files appear on the **Delivery** tab — masters, social cuts, captions and thumbnails — ready to download." },
  { slug: "what-files-should-i-send", title: "What files should I send?", category: "Files", content: "Send raw footage, separate audio if you have it, your logo (PNG or SVG), brand colours and fonts, a script or talking points, references you like, and any music. Your project setup form lists exactly what's needed for your type of video." },
  { slug: "how-does-payment-work", title: "How does payment work?", category: "Payments", content: "1. Accept your quote.\n2. Sign the agreement.\n3. Pay the invoice — your project starts immediately.\n4. Approve the final version and pay any remaining balance to unlock final files." },
];

// ───────────────────────────── project types & templates ─────────────────────────────

export const PROJECT_TYPES: { key: string; name: string; days: number; rev: number; cats: string[] }[] = [
  { key: "short_form", name: "Short-form", days: 3, rev: 2, cats: ["SHORT_FORM", "CREATOR"] },
  { key: "long_form", name: "Long-form / YouTube", days: 5, rev: 2, cats: ["CREATOR", "YOUTUBE"] },
  { key: "podcast", name: "Podcast", days: 4, rev: 2, cats: ["PODCAST"] },
  { key: "real_estate", name: "Real estate", days: 3, rev: 2, cats: ["REAL_ESTATE"] },
  { key: "motion_graphics", name: "Motion graphics", days: 6, rev: 2, cats: ["MOTION"] },
  { key: "vsl", name: "VSL", days: 7, rev: 3, cats: ["VSL"] },
  { key: "ads", name: "Ad creative", days: 3, rev: 2, cats: ["ADS"] },
  { key: "corporate", name: "Corporate", days: 6, rev: 3, cats: ["CORPORATE"] },
  { key: "saas", name: "SaaS / product", days: 5, rev: 2, cats: ["SAAS"] },
];

export const TEMPLATES: { name: string; description: string; projectTypeKey: string; days: number; rev: number; tasks: { title: string; subtasks?: string[] }[]; deliverables: { label: string; quantity: number }[]; requiredAssets: string[] }[] = [
  {
    name: "Podcast Full Package",
    description: "One recorded episode → full episode, YouTube cut, 3 Shorts, thumbnail and captions.",
    projectTypeKey: "podcast",
    days: 4,
    rev: 2,
    tasks: [
      { title: "Download footage" },
      { title: "Sync multicam" },
      { title: "Audio cleanup" },
      { title: "Colour correction" },
      { title: "Edit full episode", subtasks: ["Assembly cut", "Fine cut", "Intro / outro"] },
      { title: "Graphics" },
      { title: "Captions" },
      { title: "Internal review" },
      { title: "Export" },
      { title: "Upload to client review" },
      { title: "Apply revisions" },
      { title: "Final delivery" },
    ],
    deliverables: [{ label: "Full episode", quantity: 1 }, { label: "YouTube version", quantity: 1 }, { label: "Shorts", quantity: 3 }, { label: "Thumbnail", quantity: 1 }, { label: "Caption file", quantity: 1 }],
    requiredAssets: ["Episode recording (all camera angles)", "Clean audio tracks", "Brand logo (PNG or SVG)"],
  },
  {
    name: "YouTube Long-form",
    description: "Retention-focused long-form edit with chapters and captions.",
    projectTypeKey: "long_form",
    days: 5,
    rev: 2,
    tasks: [{ title: "Review brief & footage" }, { title: "Assembly cut" }, { title: "Story & pacing pass" }, { title: "B-roll & graphics" }, { title: "Sound design & mix" }, { title: "Colour correction" }, { title: "Captions" }, { title: "Internal review" }, { title: "Export & upload for review" }, { title: "Revisions" }, { title: "Final delivery" }],
    deliverables: [{ label: "YouTube master (16:9)", quantity: 1 }, { label: "Caption file", quantity: 1 }],
    requiredAssets: ["Raw footage", "Script or talking points", "Brand logo (PNG or SVG)"],
  },
  {
    name: "Short-Form Batch",
    description: "A batch of vertical clips with captions and sound design.",
    projectTypeKey: "short_form",
    days: 3,
    rev: 2,
    tasks: [{ title: "Select best moments" }, { title: "Cut & hook optimisation" }, { title: "Captions & motion" }, { title: "Sound design" }, { title: "Internal review" }, { title: "Export & upload for review" }, { title: "Revisions" }, { title: "Final delivery" }],
    deliverables: [{ label: "Vertical shorts (9:16)", quantity: 10 }],
    requiredAssets: ["Long-form source video or raw clips", "Brand logo (PNG or SVG)"],
  },
  {
    name: "Real Estate Listing",
    description: "Cinematic listing tour + vertical reel with agent branding.",
    projectTypeKey: "real_estate",
    days: 3,
    rev: 2,
    tasks: [{ title: "Import & organise footage" }, { title: "Cut tour" }, { title: "Colour & exposure" }, { title: "Agent branding" }, { title: "Music & sound" }, { title: "Vertical reel" }, { title: "MLS-compliant version" }, { title: "Internal review" }, { title: "Export & upload" }, { title: "Revisions" }, { title: "Final delivery" }],
    deliverables: [{ label: "Horizontal tour (16:9)", quantity: 1 }, { label: "Vertical reel (9:16)", quantity: 1 }, { label: "MLS-compliant version", quantity: 1 }],
    requiredAssets: ["Property footage / photos", "Agent logo (PNG or SVG)", "Agent contact details"],
  },
  {
    name: "VSL Production",
    description: "Script-driven video sales letter with hook variations.",
    projectTypeKey: "vsl",
    days: 7,
    rev: 3,
    tasks: [{ title: "Script review" }, { title: "Assembly & structure" }, { title: "On-screen text & proof" }, { title: "Sound design" }, { title: "Hook variations" }, { title: "Internal review" }, { title: "Export & upload" }, { title: "Revisions" }, { title: "Final delivery" }],
    deliverables: [{ label: "VSL master", quantity: 1 }, { label: "Alternate hooks", quantity: 3 }],
    requiredAssets: ["Final script", "Voiceover or talking-head recording", "Brand assets"],
  },
];

// ───────────────────────────── email templates ─────────────────────────────

export const EMAIL_TEMPLATES: { key: string; name: string; subject: string; body: string; variables: string[] }[] = [
  { key: "welcome", name: "Welcome email", subject: "Welcome to {{business_name}}, {{client_name}}", body: "Hi {{client_name}},\n\nYour account is ready. From your portal you can start a project, upload files, review edits and pay invoices — all in one place.\n\nPlease confirm your email address so we can connect your account to any projects we've set up for you:\n\n[[Confirm email|{{verify_url}}]]\n\nIf you didn't create this account, you can ignore this message.", variables: ["client_name", "verify_url", "dashboard_url"] },
  { key: "magic_link", name: "Magic sign-in link", subject: "Your sign-in link for {{business_name}}", body: "Hi {{client_name}},\n\nUse the button below to sign in. The link works once and expires in 15 minutes.\n\n[[Sign in|{{magic_url}}]]\n\nIf you didn't request this, you can safely ignore it.", variables: ["client_name", "magic_url"] },
  { key: "password_reset", name: "Password reset", subject: "Reset your {{business_name}} password", body: "Hi {{client_name}},\n\nWe received a request to reset your password. The link below is valid for one hour.\n\n[[Choose a new password|{{reset_url}}]]\n\nIf you didn't ask for this, no action is needed.", variables: ["client_name", "reset_url"] },
  { key: "invite", name: "Portal invite", subject: "You're invited to {{business_name}}", body: "Hi {{client_name}},\n\nYou've been invited to {{business_name}}. Set your password to access your projects, files and invoices.\n\n[[Accept invite|{{invite_url}}]]\n\nThis invite is valid for 7 days.", variables: ["client_name", "invite_url"] },
  { key: "lead_received", name: "Lead received (confirmation)", subject: "We've received your project request ({{request_id}})", body: "Hi {{client_name}},\n\nThanks for your request — it's in. Here's what you sent:\n\nRequest ID: {{request_id}}\nProject type: {{project_type}}\nExpected response: {{response_time}}\n\nWhat happens next: we'll review your details and reply with next steps — usually a short call or a fixed-scope quote.\n\nKeep your request ID handy if you need to reach us.", variables: ["client_name", "request_id", "project_type", "response_time"] },
  { key: "contact_received", name: "Contact form received", subject: "Thanks for getting in touch", body: "Hi {{client_name}},\n\nThanks for your message — we'll get back to you within one business day.\n\n— {{business_name}}", variables: ["client_name"] },
  { key: "meeting_booked", name: "Meeting booked", subject: "Confirmed: {{meeting_type}} on {{meeting_time}}", body: "Hi {{client_name}},\n\nYour {{meeting_type}} is confirmed for {{meeting_time}}.\n\n[[Join the meeting|{{meeting_url}}]]\n\nNeed to reschedule? Just reply to this email.", variables: ["client_name", "meeting_type", "meeting_time", "meeting_url"] },
  { key: "quote_sent", name: "Quote sent", subject: "Your quote {{quote_number}} is ready", body: "Hi {{client_name}},\n\nYour quote for {{project_name}} is ready to review — {{amount}}.\n\n[[Review your quote|{{quote_url}}]]\n\nYou can accept it in one click, or reply with any questions.", variables: ["client_name", "project_name", "amount", "quote_number", "quote_url"] },
  { key: "quote_accepted", name: "Quote accepted", subject: "Thanks — quote {{quote_number}} accepted", body: "Hi {{client_name}},\n\nThanks for accepting quote {{quote_number}} for {{project_name}}. Next we'll send the agreement for your signature.\n\n[[Open your project|{{project_url}}]]", variables: ["client_name", "project_name", "quote_number", "project_url"] },
  { key: "contract_sent", name: "Contract sent", subject: "Your agreement for {{project_name}} is ready to sign", body: "Hi {{client_name}},\n\nYour agreement for {{project_name}} is ready. Please review and sign so we can lock in your slot.\n\n[[Review & sign|{{contract_url}}]]", variables: ["client_name", "project_name", "contract_url"] },
  { key: "contract_signed", name: "Contract signed", subject: "Agreement signed — next step: payment", body: "Hi {{client_name}},\n\nThank you for signing the agreement for {{project_name}}. Your invoice is ready — payment activates your project.\n\n[[View invoice|{{invoice_url}}]]", variables: ["client_name", "project_name", "invoice_url"] },
  { key: "invoice_sent", name: "Invoice sent", subject: "Invoice {{invoice_number}} — {{amount}}", body: "Hi {{client_name}},\n\nInvoice {{invoice_number}} for {{project_name}} is ready: {{amount}}.\n\n[[View & pay invoice|{{invoice_url}}]]", variables: ["client_name", "project_name", "invoice_number", "amount", "invoice_url"] },
  { key: "invoice_reminder", name: "Invoice reminder", subject: "Reminder: invoice {{invoice_number}} is due", body: "Hi {{client_name}},\n\nA friendly reminder that invoice {{invoice_number}} ({{amount}}) is due.\n\n[[View & pay invoice|{{invoice_url}}]]\n\nAlready paid? Thank you — please ignore this note.", variables: ["client_name", "invoice_number", "amount", "invoice_url"] },
  { key: "invoice_overdue", name: "Invoice overdue", subject: "Invoice {{invoice_number}} is overdue", body: "Hi {{client_name}},\n\nInvoice {{invoice_number}} ({{amount}}) is now overdue. Please settle it when you can so we can keep your projects moving.\n\n[[View & pay invoice|{{invoice_url}}]]\n\nIf there's an issue, reply and we'll help.", variables: ["client_name", "invoice_number", "amount", "invoice_url"] },
  { key: "payment_received", name: "Payment received", subject: "Payment received — thank you", body: "Hi {{client_name}},\n\nWe've received your payment of {{amount}} for invoice {{invoice_number}}. Thank you!\n\n[[Open your project|{{project_url}}]]", variables: ["client_name", "amount", "invoice_number", "project_url"] },
  { key: "project_started", name: "Project started", subject: "Your project {{project_name}} has started", body: "Hi {{client_name}},\n\nPayment received — {{project_name}} ({{project_id}}) is now active. Next, complete the short project setup so your editor has everything they need.\n\n[[Complete project setup|{{project_url}}]]", variables: ["client_name", "project_name", "project_id", "project_url"] },
  { key: "file_request", name: "Action required: file request", subject: "Action required: {{detail}}", body: "Hi {{client_name}},\n\nTo keep {{project_name}} on schedule we need: {{detail}}.\n\n[[Upload it now|{{project_url}}]]", variables: ["client_name", "project_name", "detail", "project_url"] },
  { key: "draft_ready", name: "Draft ready", subject: "Your {{version_label}} of {{project_name}} is ready to review", body: "Hi {{client_name}},\n\n{{version_label}} of {{project_name}} is ready. Watch it, leave timestamped notes on the timeline, then approve it or request changes.\n\n[[Review the video|{{review_url}}]]", variables: ["client_name", "project_name", "version_label", "review_url"] },
  { key: "revision_received", name: "Revision received", subject: "Revision request received — {{project_name}}", body: "Hi {{client_name}},\n\nWe've got your notes for {{project_name}} and your editor is on it. You'll be notified when the next version is ready.\n\n[[View project|{{project_url}}]]", variables: ["client_name", "project_name", "project_url"] },
  { key: "revision_completed", name: "Revision completed", subject: "Your revision is ready — {{project_name}}", body: "Hi {{client_name}},\n\nYour revision on {{project_name}} is done — {{version_label}} is ready to review.\n\n[[Review the new version|{{review_url}}]]", variables: ["client_name", "project_name", "version_label", "review_url"] },
  { key: "approval_required", name: "Final approval required", subject: "Final approval needed — {{project_name}}", body: "Hi {{client_name}},\n\nThe final cut of {{project_name}} is ready. When you're happy, approve it to receive your files.\n\n[[Review & approve|{{review_url}}]]", variables: ["client_name", "project_name", "review_url"] },
  { key: "project_approved", name: "Project approved", subject: "Approved — thank you, {{client_name}}", body: "Hi {{client_name}},\n\nYou approved {{project_name}}. We're preparing your final deliverables now and will notify you as soon as they're ready to download.\n\n[[Open project|{{project_url}}]]", variables: ["client_name", "project_name", "project_url"] },
  { key: "deliverables_ready", name: "Final files ready", subject: "Your final files are ready — {{project_name}}", body: "Hi {{client_name}},\n\nYour final files for {{project_name}} are ready to download.\n\n[[Download your files|{{project_url}}]]", variables: ["client_name", "project_name", "project_url"] },
  { key: "project_delivered", name: "Project delivered", subject: "{{project_name}} has been delivered", body: "Hi {{client_name}},\n\n{{project_name}} is complete and delivered. Thank you for working with us — need another video? Start a new project anytime and we'll reuse your saved brand kit.\n\n[[Start a new project|{{dashboard_url}}]]", variables: ["client_name", "project_name", "dashboard_url"] },
  { key: "testimonial_request", name: "Testimonial request", subject: "How was your experience?", body: "Hi {{client_name}},\n\nThanks again for {{project_name}}. Would you share a quick rating and a line or two about working with us? We only publish feedback with your permission.\n\n[[Share feedback|{{project_url}}]]", variables: ["client_name", "project_name", "project_url"] },
  { key: "retainer_renewal", name: "Retainer renewal", subject: "Your monthly plan has renewed", body: "Hi {{client_name}},\n\nYour monthly plan renewed and your new allowance is available. Your invoice {{invoice_number}} ({{amount}}) is ready.\n\n[[View invoice|{{invoice_url}}]]", variables: ["client_name", "invoice_number", "amount", "invoice_url"] },
  { key: "new_message", name: "New message", subject: "New message on {{project_name}}", body: "Hi {{client_name}},\n\nYou have a new message:\n\n“{{message_preview}}”\n\n[[Read & reply|{{action_url}}]]", variables: ["client_name", "project_name", "message_preview", "action_url"] },
  { key: "project_assigned", name: "Project assigned (team)", subject: "You've been assigned to {{project_name}}", body: "Hi {{user_name}},\n\nYou've been assigned to {{project_name}} ({{project_id}}).\n\n[[Open project|{{project_url}}]]", variables: ["user_name", "project_name", "project_id", "project_url"] },
  { key: "notification", name: "Generic notification", subject: "{{title}}", body: "{{message}}\n\n[[Open in portal|{{action_url}}]]", variables: ["title", "message", "action_url"] },
];

// ───────────────────────────── default automations ─────────────────────────────

export interface AutoSeed {
  name: string;
  description: string;
  event: string;
  conditions?: unknown;
  actions: { type: "EMAIL" | "NOTIFICATION" | "STATUS_UPDATE" | "CREATE_TASK" | "ADMIN_ALERT" | "CLIENT_REMINDER"; config: Record<string, unknown>; delayMinutes?: number }[];
}

const N = (recipient: string, title: string, message: string, link: string, category = "PROJECT", extra: Record<string, unknown> = {}) => ({ type: "NOTIFICATION" as const, config: { recipient, title, message, link, category, ...extra } });
const E = (recipient: string, templateKey: string, category = "PROJECT", extra: Record<string, unknown> = {}) => ({ type: "EMAIL" as const, config: { recipient, templateKey, category, ...extra } });

export const AUTOMATIONS: AutoSeed[] = [
  { name: "New lead → alert the team", description: "Tells admins the moment a lead arrives.", event: "lead.created", actions: [{ type: "ADMIN_ALERT", config: { recipient: "admins", title: "New lead: {{lead_name}}", message: "Request {{request_id}} needs a reply.", link: "/admin/leads/{{lead_pid}}", category: "SYSTEM" } }] },
  { name: "Lead assigned → notify owner", description: "Notifies the team member a lead is assigned to.", event: "lead.assigned", actions: [N("lead_owner", "A lead was assigned to you", "{{lead_name}} — {{request_id}}", "/admin/leads/{{lead_pid}}", "SYSTEM")] },
  { name: "Follow-up due → remind owner", description: "Reminds the lead owner when a follow-up date arrives.", event: "lead.follow_up_due", actions: [N("lead_owner", "Follow-up due: {{lead_name}}", "It's time to follow up on {{request_id}}.", "/admin/leads/{{lead_pid}}", "SYSTEM")] },
  { name: "Quote sent → notify client", description: "In-app + email, then a reminder after 3 days if it's still open.", event: "quote.sent", actions: [N("client", "Your quote is ready", "{{project_name}} — {{amount}}", "{{base}}/quotes/{{quote_pid}}", "PAYMENT"), E("client", "quote_sent", "PAYMENT"), { type: "CLIENT_REMINDER", delayMinutes: 4320, config: { recipient: "client", title: "Your quote is still waiting for you", message: "{{project_name}} — {{amount}}", link: "{{base}}/quotes/{{quote_pid}}", category: "PAYMENT", onlyIf: "quote_open" } }] },
  { name: "Quote accepted → alert team, thank client", description: "Admins know to send the contract; the client gets a confirmation.", event: "quote.accepted", actions: [{ type: "ADMIN_ALERT", config: { recipient: "admins", title: "Quote accepted: {{quote_number}}", message: "{{client_name}} accepted — send the contract.", link: "/admin/projects/{{project_pid}}", category: "PAYMENT" } }, E("client", "quote_accepted", "PAYMENT")] },
  { name: "Quote declined → alert team", description: "", event: "quote.rejected", actions: [{ type: "ADMIN_ALERT", config: { recipient: "admins", title: "Quote declined: {{quote_number}}", message: "{{client_name}} declined the quote.", link: "/admin/quotes/{{quote_pid}}", category: "PAYMENT" } }] },
  { name: "Contract sent → notify client", description: "Notify + email, reminder after 2 days if unsigned.", event: "contract.sent", actions: [N("client", "Your contract is ready to sign", "{{project_name}}", "{{base}}/contracts/{{contract_pid}}", "PROJECT"), E("client", "contract_sent"), { type: "CLIENT_REMINDER", delayMinutes: 2880, config: { recipient: "client", title: "Your agreement is waiting for your signature", message: "{{project_name}}", link: "{{base}}/contracts/{{contract_pid}}", onlyIf: "contract_unsigned" } }] },
  { name: "Contract signed → alert team, email client", description: "", event: "contract.signed", actions: [{ type: "ADMIN_ALERT", config: { recipient: "admins", title: "Contract signed: {{project_name}}", message: "{{client_name}} signed — invoice issued.", link: "/admin/projects/{{project_pid}}", category: "PAYMENT" } }, E("client", "contract_signed", "PAYMENT")] },
  { name: "Invoice sent → notify client", description: "Reminder after 3 days if unpaid.", event: "invoice.sent", actions: [N("client_billing", "Your invoice is due", "{{invoice_number}} — {{amount}}", "{{base}}/invoices/{{invoice_pid}}", "PAYMENT"), E("client_billing", "invoice_sent", "PAYMENT"), { type: "CLIENT_REMINDER", delayMinutes: 4320, config: { recipient: "client_billing", title: "Invoice {{invoice_number}} is still open", message: "{{amount}}", link: "{{base}}/invoices/{{invoice_pid}}", category: "PAYMENT", templateKey: "invoice_reminder", onlyIf: "invoice_unpaid" } }] },
  { name: "Invoice due soon → remind client", description: "", event: "invoice.due_soon", actions: [{ type: "CLIENT_REMINDER", config: { recipient: "client_billing", title: "Invoice {{invoice_number}} is due soon", message: "{{amount}}", link: "{{base}}/invoices/{{invoice_pid}}", category: "PAYMENT", templateKey: "invoice_reminder", onlyIf: "invoice_unpaid" } }] },
  { name: "Invoice overdue → chase client, alert finance", description: "", event: "invoice.overdue", actions: [{ type: "CLIENT_REMINDER", config: { recipient: "client_billing", title: "Invoice {{invoice_number}} is overdue", message: "{{amount}}", link: "{{base}}/invoices/{{invoice_pid}}", category: "PAYMENT", templateKey: "invoice_overdue" } }, { type: "ADMIN_ALERT", config: { recipient: "finance", title: "Invoice {{invoice_number}} is overdue", message: "{{client_name}} — {{amount}}", link: "/admin/invoices/{{invoice_pid}}", category: "PAYMENT" } }] },
  { name: "Payment received → thank client, alert finance", description: "", event: "payment.received", actions: [N("client_billing", "Payment received", "Thank you — {{amount}} for {{invoice_number}}", "{{base}}/invoices/{{invoice_pid}}", "PAYMENT"), E("client_billing", "payment_received", "PAYMENT"), { type: "ADMIN_ALERT", config: { recipient: "finance", title: "Payment received: {{amount}}", message: "{{client_name}} · {{invoice_number}}", link: "/admin/invoices/{{invoice_pid}}", category: "PAYMENT" } }] },
  { name: "Project activated → kick off onboarding", description: "Client is told the project started; the team gets an 'assign editor' task.", event: "project.activated", actions: [N("client", "Your project has started", "{{project_name}} — complete the project setup so we can begin", "{{base}}/projects/{{project_pid}}/setup", "PROJECT"), E("client", "project_started"), { type: "ADMIN_ALERT", config: { recipient: "admins", title: "Project activated: {{project_name}}", message: "Assign an editor.", link: "/admin/projects/{{project_pid}}", category: "PROJECT" } }, { type: "CREATE_TASK", config: { assignee: "manager", taskTitle: "Assign an editor & review the project brief", priority: "HIGH", dueInDays: 1 } }] },
  { name: "Onboarding complete → tell the team", description: "", event: "onboarding.completed", actions: [N("manager", "Brief received: {{project_name}}", "The client completed the project brief.", "/admin/projects/{{project_pid}}", "PROJECT"), N("client", "Brief received — thank you", "Now upload your footage and assets.", "{{base}}/projects/{{project_pid}}?tab=files", "PROJECT")] },
  { name: "Client uploaded everything → ready to edit", description: "", event: "assets.ready", actions: [N("team", "Assets are ready: {{project_name}}", "The client confirmed all files are uploaded.", "{{base}}/projects/{{project_pid}}", "PROJECT"), N("manager", "Assets are ready: {{project_name}}", "Queue an editor to start.", "/admin/projects/{{project_pid}}", "PROJECT")] },
  { name: "Files uploaded → notify team", description: "", event: "files.uploaded", actions: [N("team", "New files from the client", "{{detail}} — {{project_name}}", "{{base}}/projects/{{project_pid}}?tab=files", "PROJECT"), N("manager", "New files from the client", "{{detail}} — {{project_name}}", "/admin/projects/{{project_pid}}?tab=files", "PROJECT")] },
  { name: "File requested → tell client", description: "Shows as 'Action required' in the portal.", event: "file_request.created", actions: [N("client", "Action required: {{detail}}", "{{project_name}}", "{{base}}/projects/{{project_pid}}?tab=files", "PROJECT"), E("client", "file_request")] },
  { name: "Change request → alert manager", description: "", event: "change_request.created", actions: [N("manager", "Change request: {{project_name}}", "Review and classify the request.", "/admin/projects/{{project_pid}}?tab=scope", "PROJECT"), { type: "ADMIN_ALERT", config: { recipient: "admins", title: "Change request: {{project_name}}", message: "Included, out of scope, or extra cost?", link: "/admin/projects/{{project_pid}}?tab=scope" } }] },
  { name: "Draft uploaded → tell client", description: "In-app + email: 'Your draft is ready for review'.", event: "draft.uploaded", actions: [N("client", "Your {{version_label}} is ready for review", "{{project_name}}", "{{base}}/projects/{{project_pid}}/review/{{version_pid}}", "REVIEW"), E("client", "draft_ready", "REVIEW"), { type: "CLIENT_REMINDER", delayMinutes: 4320, config: { recipient: "client", title: "Your draft is still waiting for review", message: "{{project_name}} — {{version_label}}", link: "{{base}}/projects/{{project_pid}}/review/{{version_pid}}", category: "REVIEW", onlyIf: "review_pending" } }] },
  { name: "Revision submitted → editor & manager", description: "Creates a task so the revision is never missed.", event: "revision.submitted", actions: [N("editors", "Revision requested: {{project_name}}", "The client sent notes on {{version_label}}.", "{{base}}/projects/{{project_pid}}/review/{{version_pid}}", "REVIEW"), N("manager", "Revision requested: {{project_name}}", "The client sent notes on {{version_label}}.", "/admin/projects/{{project_pid}}/review/{{version_pid}}", "REVIEW"), E("client", "revision_received", "REVIEW"), { type: "CREATE_TASK", config: { assignee: "editor", taskTitle: "Apply revision notes on {{version_label}}", priority: "HIGH", dueInDays: 2 } }] },
  { name: "Revision completed → tell client", description: "", event: "revision.completed", actions: [N("client", "A revision has been completed", "{{version_label}} of {{project_name}} is ready to review.", "{{base}}/projects/{{project_pid}}/review/{{version_pid}}", "REVIEW"), E("client", "revision_completed", "REVIEW")] },
  { name: "Project approved → celebrate & prepare delivery", description: "", event: "project.approved", actions: [N("editors", "Approved: {{project_name}}", "Prepare and upload the final deliverables.", "{{base}}/projects/{{project_pid}}", "PROJECT"), N("manager", "Approved: {{project_name}}", "Upload and publish the final deliverables.", "/admin/projects/{{project_pid}}", "PROJECT"), E("client", "project_approved"), { type: "CREATE_TASK", config: { assignee: "manager", taskTitle: "Upload & publish final deliverables", priority: "HIGH", dueInDays: 1 } }] },
  { name: "Final files published → tell client", description: "", event: "deliverables.published", actions: [N("client", "Your final files are ready", "{{project_name}} — download them from the Delivery tab", "{{base}}/projects/{{project_pid}}?tab=delivery", "PROJECT"), E("client", "deliverables_ready")] },
  { name: "Project delivered → thank client", description: "", event: "project.delivered", actions: [E("client", "project_delivered")] },
  { name: "Retainer renewed → invoice notice", description: "", event: "retainer.renewed", actions: [N("client_billing", "Your monthly plan renewed", "{{invoice_number}} — {{amount}}", "{{base}}/invoices/{{invoice_pid}}", "PAYMENT"), E("client_billing", "retainer_renewal", "PAYMENT")] },
  { name: "Deadline approaching → warn the team", description: "", event: "project.deadline_soon", actions: [N("team", "Deadline approaching: {{project_name}}", "Due {{deadline}}.", "{{base}}/projects/{{project_pid}}", "PROJECT"), N("manager", "Deadline approaching: {{project_name}}", "Due {{deadline}}.", "/admin/projects/{{project_pid}}", "PROJECT")] },
  { name: "Ready for internal review → notify manager", description: "Fires when a project enters internal review.", event: "project.status_changed", conditions: { all: [{ field: "to", op: "eq", value: "INTERNAL_REVIEW" }] }, actions: [N("manager", "Ready for internal review: {{project_name}}", "Review before it goes to the client.", "/admin/projects/{{project_pid}}", "REVIEW")] },
];
