import { BASE, check, launch, done } from "./lib.mjs";
import { execFileSync } from "node:child_process";
import { writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const { browser, ctx, page, errors } = await launch();
const q = (key) => page.locator(`[data-q="${key}"]`);
const heading = async () => (await page.locator("[data-title]").innerText()).trim();
const next = async () => { await page.locator("[data-next]").click(); await page.waitForTimeout(250); };
const pick = async (key, value) => { await q(key).locator(`input[value="${value}"]`).evaluate((i) => i.closest("label").click()); await page.waitForTimeout(120); };
const fill = async (key, value) => { await q(key).locator("input,textarea").first().fill(String(value)); await page.waitForTimeout(80); };
const select = async (key, value) => { await q(key).locator("select").selectOption(value); await page.waitForTimeout(120); };
const visible = async (key) => (await q(key).count()) > 0;

console.log("Step 1: required answer + conditional categories");
await page.goto(BASE + "/start-project", { waitUntil: "networkidle" });
check("wizard renders the first question", (await heading()).includes("looking for"), await heading());
await next();
check("Continue without answering shows a required error", (await q("looking_for").locator("[data-err]").innerText()).includes("required"));
check("step counter starts at 1", (await page.locator("[data-step]").innerText()).startsWith("Step 1 of"));
await pick("looking_for", "real_estate");
check("error clears once answered", (await q("looking_for").locator("[data-err]").innerText()) === "");
await next();
check("moved to step 2 (client type)", (await heading()).includes("type of client"), await heading());
await page.locator("[data-back]").click(); await page.waitForTimeout(200);
check("Back returns to step 1 with the answer kept", (await q("looking_for").locator("input:checked").getAttribute("value")) === "real_estate");
await next();
await pick("client_type", "business");
await next();
check("details step shows the real-estate questions", await visible("property_type"));
check("podcast-only questions stay hidden", !(await visible("podcast_name")));
check("category-gated question hidden until a matching niche is chosen", !(await visible("youtube_channel")));
await select("niche", "youtube_creator");
check("YouTube niche enables the channel question's category but its own rule still hides it", !(await visible("youtube_channel")));
await q("platforms").locator('input[value="youtube"]').evaluate((i) => i.closest("label").click()); await page.waitForTimeout(150);
check("choosing YouTube reveals the channel URL question", await visible("youtube_channel"));
await fill("youtube_channel", "not a url");
await select("property_type", "house");
await next();
check("invalid URL blocks the step", (await q("youtube_channel").locator("[data-err]").innerText()).toLowerCase().includes("valid url"));
await fill("youtube_channel", "https://youtube.com/@harborview");
await q("platforms").locator('input[value="youtube"]').evaluate((i) => i.closest("label").click()); await page.waitForTimeout(150);
check("un-choosing YouTube hides the channel question again", !(await visible("youtube_channel")));
await select("niche", "podcast");
check("changing niche switches question sets on (podcast) and off (real estate options stay via looking_for)", await visible("podcast_name"));
await select("niche", "real_estate");
await next();
check("workflow step reached", (await heading()).toLowerCase().includes("workflow"), await heading());
await select("video_frequency", "weekly");
check("frequency 'weekly' asks how many videos per month", await visible("videos_per_month"));
await select("video_frequency", "one_time");
check("frequency 'one_time' hides that question", !(await visible("videos_per_month")));
await next();
check("budget step reached", (await heading()).toLowerCase().includes("budget"));
await pick("budget", "500_1000");
await next();
await next(); // style (optional)
check("contact step reached", (await heading()).toLowerCase().includes("contact"), await heading());
await fill("name", "Wizard Tester"); await fill("email", "nope");
await next();
check("invalid email blocked", (await q("email").locator("[data-err]").innerText()).toLowerCase().includes("valid email"));
await fill("email", "wizard.tester@example.com");
await next();
check("description step reached", (await heading()).toLowerCase().includes("project"), await heading());
await fill("project_description", "short");
await next();
check("minimum-length rule enforced", (await q("project_description").locator("[data-err]").innerText()).toLowerCase().includes("at least"));
await fill("project_description", "We need a 90 second cinematic walkthrough for a three bedroom harbour view house, with captions and a vertical cut for Instagram.");
await next();

console.log("Reference-file upload (anonymous, signed short-lived target)");
check("uploads step reached", (await heading()).toLowerCase().includes("reference"), await heading());
const tmp = mkdtempSync(join(tmpdir(), "wiz-"));
const good = join(tmp, "brief.pdf"); writeFileSync(good, "%PDF-1.4\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF\n");
await page.locator('[data-q="references"] input[type=file]').setInputFiles(good);
await page.waitForSelector('[data-q="references"] li:has-text("Uploaded")', { timeout: 10000 }).catch(() => {});
check("PDF uploads and shows as Uploaded", (await page.locator('[data-q="references"] li:has-text("Uploaded")').count()) === 1);
const bad = join(tmp, "payload.php"); writeFileSync(bad, "<?php echo 1;");
await page.locator('[data-q="references"] input[type=file]').setInputFiles(bad);
await page.waitForTimeout(1500);
check("a .php file is refused", (await page.locator('[data-q="references"] li').first().innerText()).toLowerCase().match(/not allowed|isn.t allowed|can.t|blocked|type/) !== null, (await page.locator('[data-q="references"] li').first().innerText()).replace(/\s+/g, " "));
await next();

console.log("Review + submit");
check("review step lists the answers", (await page.locator("dl").allInnerTexts()).join(" ").includes("Wizard Tester"));
await page.locator('[data-edit="budget"]').click(); await page.waitForTimeout(200);
check("Edit jumps back to that section", (await heading()).toLowerCase().includes("budget"));
await next(); await next(); await next(); await next(); await next();
check("back on review", (await heading()).toLowerCase().includes("review"), await heading());
await page.waitForTimeout(4200); // the server rejects instant submissions
await page.locator("[data-next]").click();
await page.waitForSelector("text=Request received", { timeout: 10000 }).catch(() => {});
check("submission confirmed with a request ID", (await page.content()).includes("Request received") && /FE-|REQ-|[A-Z]{2,4}-\d/.test(await page.locator("dl").innerText()), (await page.locator("dl").allInnerTexts()).join("|"));

console.log("Stored server-side");
const row = execFileSync("mariadb", ["-ufaizan", "-pfaizan_dev", "-h127.0.0.1", "faizan_php", "-N", "-e", "SELECT JSON_UNQUOTE(JSON_EXTRACT(answers,'$.looking_for')), JSON_UNQUOTE(JSON_EXTRACT(answers,'$.property_type')), email, (SELECT COUNT(*) FROM assets a WHERE a.draftToken IS NOT NULL AND a.leadId = leads.id) FROM leads WHERE email='wizard.tester@example.com' ORDER BY createdAt DESC LIMIT 1"]).toString().trim().split("\t");
check("lead saved with the chosen answers", row[0] === "real_estate" && row[1] === "house", row.join(","));
check("uploaded PDF attached to the lead", row[3] === "1", row.join(","));

console.log("Autosave + resume");
const c2 = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const p2 = await c2.newPage();
await p2.goto(BASE + "/start-project", { waitUntil: "networkidle" });
await p2.locator('[data-q="looking_for"] input[value="podcast"]').evaluate((i) => i.closest("label").click());
await p2.waitForSelector("text=Progress saved", { timeout: 5000 }).catch(() => {});
check("autosave indicator appears", (await p2.locator("[data-save]").innerText()).includes("saved"));
await p2.reload({ waitUntil: "networkidle" });
await p2.waitForSelector("[data-resume-yes]", { timeout: 5000 }).catch(() => {});
check("reload offers to resume", (await p2.locator("[data-resume-yes]").count()) === 1);
await p2.locator("[data-resume-yes]").click();
check("resume restores the earlier answer", (await p2.locator('[data-q="looking_for"] input:checked').getAttribute("value")) === "podcast");
await c2.close();

console.log("Mobile");
const c3 = await browser.newContext({ viewport: { width: 375, height: 800 } });
const p3 = await c3.newPage();
await p3.goto(BASE + "/start-project", { waitUntil: "networkidle" });
check("no horizontal scroll at 375px", await p3.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
check("Continue button is visible without scrolling", await p3.locator("[data-next]").isVisible());
await c3.close();

await browser.close();
done(errors);
